### ISSUE TITLE
CTC_loss not work~

### ISSUE THREAD

**Issue by novioleo** [solivr/tf-crnn#1]
Hey,thks for your brilliant work~
I tried install warp_ctc and bind it with tensorflow,there are so many problems.Thus,i tried your ctc_loss in code
---
        loss_ctc = tf.nn.ctc_loss(labels=sparse_code_target,
                                  inputs=predictions_dict['prob'],
                                  sequence_length=tf.cast(features['images'].shape[0], tf.int32),
                                  preprocess_collapse_repeated=False,
                                  ctc_merge_repeated=True,
                                  ignore_longer_outputs_than_inputs=False,
                                  time_major=True)
---

however,tf throw that message:
**ValueError: Shape must be rank 1 but is rank 0 for 'CTCLoss' (op: 'CTCLoss') with input shapes: [24,128,37], [?,2], [?], [].**

due to i'm a noob in tensorflow,so can you get me out of trouble?

**Comment by novioleo** [comment]
oh oops~
i made a stupid mistake~
----
the code should be:

        loss_ctc = tf.nn.ctc_loss(labels=sparse_code_target,
                                  inputs=predictions_dict['prob'],
                                  sequence_length=tf.cast(seq_lengths_labels,tf.int32),
                                  preprocess_collapse_repeated=False,
                                  ctc_merge_repeated=True,
                                  ignore_longer_outputs_than_inputs=False,
                                  time_major=True)

however,
tensorflow warning that:
**tensorflow/core/util/ctc/ctc_loss_calculator.cc:144] No valid path found.**

**Comment by novioleo** [comment]
......
i fixed it again.and i'll close this issue~
 
`
seq_lengths_labels = tf.segment_max(sparse_code_target.indices[:, 1], sparse_code_target.indices[:, 0])*2 + 1
loss_ctc = tf.nn.ctc_loss(labels=sparse_code_target,
                                  inputs=predictions_dict['prob'],
                                  sequence_length=tf.cast(seq_lengths_labels,tf.int32),
                                  preprocess_collapse_repeated=False,
                                  ctc_merge_repeated=True,
                                  ignore_longer_outputs_than_inputs=False,
                                  time_major=True)
`

**Comment by solivr** [comment]
Hi Tao,
Did you have trouble installing Baidu's warp_ctc or binding it ? From what I remember, the binding was quite straightforward, but installing Baidu's CTC was more troublesome.
I didn't use the builtin TF CTC loss because I found it to be numerically instable and couldn't converge using it. Did you manage to train your network with it ?

**Comment by novioleo** [comment]
@solivr I tried so many times to binding warp_ctc to tensorflow,however,it comes out so many problems.
i gave it up.so i tried the built-in ctc.as you said,it's so awful.

i use the built-in ctc to train the MNIST serial,it achieve the 94% acc.today i'm try to train the much more complex training,and a big wave problem is coming.

Besides,how could you binding warp-ctc to your tensorflow,can u give me some tips?
Or you just follow the official tutorial?
I follow the official tutorial three times,and tried on different computers.i'm devastated.

look forward to your reply~

**Comment by solivr** [comment]
@novioleo I refactored a lot of functions and warp_ctc from Baidu is not needed anymore! It just relies on pure nn.ctc_loss now and works fine for now

**Comment by novioleo** [comment]
@solivr thks for your reply.i had tried yet.

**Comment by HunterHantao** [comment]
Hi Solivr, 

I am trying to train the network using synthetic word dataset. I also find the warning "No valid  path found". Is this warning normal? Or any recommendation. A screenshot is attached. 
![image](https://user-images.githubusercontent.com/8010994/42359274-763a918a-8113-11e8-9b35-58bcafdd2aa6.png)

But it seems to converge. 

Thank you.

**Comment by HunterHantao** [comment]
It should be the problem "the length of the labels must be shorter than the input lengths".  Any suggestions are appreciated.

**Comment by ps48** [comment]
@novioleo Can you please help me understand how using tf.segment_max solved the issue of "No valid path found"?
