### ISSUE TITLE
hi、is python2.7 or python 3？

### ISSUE THREAD

**Issue by zhLawliet** [solivr/tf-crnn#15]

**Comment by WenmuZhou** [comment]
I think all python version is support, I use python 3.6

**Comment by zhLawliet** [comment]
ok,thanks,can you give me the model that you have trained about the mnist, there are some errors about it, thank you very much, my emai: zhlawliet@qq.com.

**Comment by WenmuZhou** [comment]
sorry，I have delete the model about one month ago

**Comment by zhLawliet** [comment]
ok, than you
