### ISSUE TITLE
CSV files

### ISSUE THREAD

**Issue by meatif** [solivr/tf-crnn#18]
I input the csv files according to your instruction but that is not working and generate following error
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expect 2 fields but have 0 in record 0 
could you please share with me csv files for training

**Comment by solivr** [comment]
Your CSV file should look like this : 
```
/my_directory/my_file.jpg;string_label1
/my_directory/my_file2.jpg;string_label2
```
If you have the latest version of the code, the CSV delimiter should be `;`.

**Comment by meatif** [comment]
Than you for the reply and the kind help previous problem has been resolved 
I'm working on urdu text recognition  
it is working with English text but giving following error with urdu text during training
"UnicodeDecodeError: 'utf-8' codec can't decode byte 0xeb in position 14: invalid continuation byte"

**Comment by solivr** [comment]
This has the same origin as this [issue](https://github.com/solivr/tf-crnn/issues/8), you can try to adapt the proposed solution.
