### ISSUE TITLE
Frozen a model issues

### ISSUE THREAD

**Issue by zdnet** [solivr/tf-crnn#28]
Hi,
thanks for your repo.
I want to export a frozen model after trained, but how to set the input & output node name?
i tried output_node_names = "code2str_conversion/predicted_words" but seems input "images" is not in graph:
ValueError: Attempted to map inputs that were not found in graph_def: [images:0]

Could you please advice how can i export a frozen model?

Thanks.

**Comment by JcmeLs** [comment]
I have the same question. And I use `input_dict, output_dict = _signature_def_to_tensors (loaded_model.signature_def ['predictions'])` to get the name of the input and output nodes. It return input node name is `Placeholder: 0`. However, I did not find this input in the graph when checkpoint was restored

**Comment by JcmeLs** [comment]
For output node,I see your code is selected `code2str_conversion / chars_conversion / cond / Merge: 0`. But when I use this as output, it can export PB, but when using this pb file to test, it will report `Table not initialized` error.

**Comment by solivr** [comment]
Hello, the updated version of the code uses tf.keras, so this should be easier to deal with.
