### ISSUE TITLE
about mkdir for ".../export/..."

### ISSUE THREAD

**Issue by IMYR666** [solivr/tf-crnn#38]
Hi @solivr :
it happens an error "can not make directory './output/export\'sequencenumber'\'",then I interrupted this code and restarted it , it was running good,but couldn't save the model to ".../export/..." directory.What might be the problem? thanks.
I run code at windows10, using CPU not GPU.

**Comment by solivr** [comment]
Hi @IMYR666,
I had a similar issue on another project, it seems that when working on Windows, the `export` directory is not created. I updated the code (01f43a43703a2dac5ad6c7876c828ee966364e39), can you try again and let me know if it works now ?

**Comment by IMYR666** [comment]
It works! thanks!

**Comment by IMYR666** [comment]
And I have another question: what is the function of "my_eval_data.csv"? just like validated data?

**Comment by solivr** [comment]
Yes, it is the csv file where you have listed your validation data.
