### ISSUE TITLE
Is there a script to test the model with one images

### ISSUE THREAD

**Issue by WenmuZhou** [solivr/tf-crnn#4]
now, I have trained a model with mnist dataset, how can I test the model?, or Is there a script ?

**Comment by WenmuZhou** [comment]
I have write a file to predict with ten image, but the output is None, 

![image](https://user-images.githubusercontent.com/12406017/32043302-f590622a-ba6c-11e7-87b9-7ff66415e10b.png)

```
# -*- coding: utf-8 -*-

try:
    import better_exceptions
except ImportError:
    pass
import tensorflow as tf
from src.model import crnn_fn
from src.data_handler import data_loader
from src.config import Params, Alphabet

parameters = Params(input_shape=(32, 304),
                    digits_only=True,
                    alphabet=Alphabet.DIGITS_ONLY,
                    csv_delimiter=' ',
                    gpu = '0'
                    )

model_params = {
    'Params': parameters,
}

os.environ['CUDA_VISIBLE_DEVICES'] = parameters.gpu
config_sess = tf.ConfigProto()
config_sess.gpu_options.per_process_gpu_memory_fraction = 0.5
config_sess.gpu_options.allow_growth = True

est_config = tf.estimator.RunConfig()
est_config.replace(keep_checkpoint_max=1,
                   save_checkpoints_steps=1000,
                   session_config=config_sess,
                   save_checkpoints_secs=None,
                   model_dir='models')

estimator = tf.estimator.Estimator(model_fn=crnn_fn,params=model_params,model_dir='models',config=est_config)

predictions = estimator.predict(input_fn=data_loader(csv_filename='data/test.csv',
                                                 params=parameters,
                                                 batch_size=128,
                                                 num_epochs=1,
                                                 data_augmentation=False,
                                                 image_summaries=False))

predicted_classes = [p["classes"] for p in predictions]

print("New Samples, Class Predictions:    {}\n".format(predicted_classes))
```

Is anywhere wrong?

**Comment by solivr** [comment]
I was not able to reproduce your error, but I added a loader class and functions in `src/loader`. You can use it this way : 
``` python
import tensorflow as tf
from src.loader import PredictionModel
from scipy.misc import imread

model_dir = '<your_model_dir>/export/<number_export>/'
image = imread('<your_image_path>.jpg', mode='L')[: ,:, None]

with tf.Session() as sess:
    model = PredictionModel(model_dir)
    predictions = model.predict(image)
    transcription = predictions['words']
```

**Comment by solivr** [comment]
I got it, you can also add the argument `predict_keys='words'` to `estimator.predict` like this : 
```python
predictions = estimator.predict(input_fn=data_loader(csv_filename=csv_filename,
                                                     params=parameters,
                                                     batch_size=100,
                                                     num_epochs=1,
                                                     data_augmentation=False,
                                                     image_summaries=False),
                                 predict_keys='words')

predicted_words = [p['words'] for p in predictions]
print("New Samples, Class Predictions:    {}\n".format(predicted_words))
```

If you want to see `score` or `probs`, just change `predict_keys`.

**Comment by WenmuZhou** [comment]
the code is work fine, thank you

**Comment by WenmuZhou** [comment]
when I get `score` from net
```python
import tensorflow as tf
from src.loader import PredictionModel
from scipy.misc import imread

model_dir = 'models/export/1508588149/'
image = imread('data/test/000000003_80149.jpg', mode='L')[: ,:, None]

with tf.Session() as sess:
    model = PredictionModel(model_dir)
    predictions = model.predict(image)
    transcription = predictions['words']
    score = predictions['score']
    print(transcription,score)
```

the result is 
![image](https://user-images.githubusercontent.com/12406017/32717615-415def20-c895-11e7-993d-2aa7d695ec33.png)

the score is greater than 1, however, in neural networks, the confidence should be less than 1, or the `score` isn't confidence？

**Comment by solivr** [comment]
If you have a look at the [line](https://github.com/solivr/tf-crnn/blob/master/src/model.py#L320) computing the score, you'll see that it's a sort of ratio between the probability of the first and second best paths of the beam decoder (since `tf.nn.ctc_beam_search_decoder` outputs log probabilities). So yes, in this case, the score can be greater than 1.

**Comment by codecolony** [comment]
@solivr Any ideas on how to convert this ratio value to confidence value of the predicted word? Sorry if this is a naive question.

Edit: I had a look into the code and found that just reading `log_probability[:, 0]` should give me log probability. I want to take inverse log but can you tell me what should be base of the log?

**Comment by solivr** [comment]
@codecolony I hadn't had any better idea at the time I implemented it, but I remember going through [this issue](https://github.com/tensorflow/tensorflow/issues/6034) which seems to show some inconsistancies... 
I would have to check it before giving you an answer, because it's not clear from the documentation and the code is not helping either...
