### ISSUE TITLE
when I use tf 1.8 to train the code,the gpu util is 0 always

### ISSUE THREAD

**Issue by WenmuZhou** [solivr/tf-crnn#43]
![image](https://user-images.githubusercontent.com/12406017/42431154-6c174a62-8376-11e8-8864-f2d07ead706a.png)

**Comment by solivr** [comment]
I changed [this line](https://github.com/solivr/tf-crnn/blob/master/train.py#L26) so that the device name is composed programmatically. Can you give it a new try ?

**Comment by WenmuZhou** [comment]
![image](https://user-images.githubusercontent.com/12406017/42451645-70a0d1cc-83ba-11e8-92fd-bdb60498c17e.png)
There will be fluctuations at the beginning, and it will be 0 after that and it will stop here.
![image](https://user-images.githubusercontent.com/12406017/42451714-a7ce2cc6-83ba-11e8-8b79-daf55dd92ef2.png)

**Comment by solivr** [comment]
Does the usage stay at zero once the training starts ? 
Your GPU should start being used after the buffer (Dataset) is filled, i.e after the log message:
```
I tensorflow/core/kernels/data/shuffle_dataset_op.cc:94] Filling up shuffle buffer (this may take a while): 1885 of 2048
I tensorflow/core/kernels/data/shuffle_dataset_op.cc:129] Shuffle buffer filled.
```
Otherwise, I am not able to reproduce your error...
