### ISSUE TITLE
Why do the new codes run so slowly?

### ISSUE THREAD

**Issue by the-butterfly** [solivr/tf-crnn#44]
I have trained the model on a data set containing 200, 000 images using codes of 0.5 version.
But the training speed is really slow ...
It have 0.07 global_step/s and elapsed 4 h to achieve 1k steps.
Meanwhile, the old version (0.3.0) codes,  running on the same data set, have 1.6 global_step/s and only consumed 30 min achieving 1k steps.
The hyper-parameters are the same except batch size (128 for old one, 256 for the new one).
I can hardly figure out why.
Could anyone show me the cause?

**Comment by the-butterfly** [comment]
In Addition, I use  **Unicode** in experiment.
And in another experiment on `IIIT5k` (different machine), it seems the new version has 2.x speed in contrast to the old one.

**Comment by solivr** [comment]
I don't know why you have slower training, but if you want quicker training, you can try to change tf.nn.ctc_loss to [Baidu's ctc implementation](https://github.com/baidu-research/warp-ctc) which will allow you to use your GPU (instead of CPU usage for tensorflow's implementation)

**Comment by the-butterfly** [comment]
Anyway, thanks for your reply. Maybe I should have a try.

**Comment by solivr** [comment]
Hi,
The updated `input_fn` should be much faster now, you can pull the new version. I made some changes according to the suggestions in [this issue](https://github.com/tensorflow/tensorflow/issues/18784).

**Comment by the-butterfly** [comment]
OK, I'll have a try. thx.
