### ISSUE TITLE
How to test and print the prediction results of my own trained model?

### ISSUE THREAD

**Issue by Usmankhujaev** [solivr/tf-crnn#48]
I trained my own model using my own images with their ground truth values and I saw evaluation accuracy at the end of training but I couldn't test different image to see the predicted values for my trained model

**Comment by zhangxu5515** [comment]
Hi, @Usmankhujaev. Uh.... Did you find way to print the prediction results? I can only get some tensors such as probs:... words:.... but not predicted words.

**Comment by solivr** [comment]
Hello, the updated version of the code has a `prediction.py` file which outputs the recognized text in a text file, you can try it.
