### ISSUE TITLE
Serving tf_serving

### ISSUE THREAD

**Issue by matheusgmaia** [solivr/tf-crnn#49]
I had several problems at serving one trainned model with tensorflow_serving docker, I run into this error:
`
"Generic conv implementation does not support grouped convolutions for now.\\n\\t [[{{node deep_cnn/layer1/conv}}]]"`

Do you have any tips about how to de-group this "grouped convolution" at deep_cnn or how to serve the model in a REST API?

**Comment by XinyuDu** [comment]
same error

**Comment by XinyuDu** [comment]
Should convert the image to gray befor input the model.
`image = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
image = np.expand_dims(image, -1)`
