### ISSUE TITLE
ctc_loss_calculator.cc no valid path found

### ISSUE THREAD

**Issue by jylei66** [solivr/tf-crnn#50]
When I train my own net, I got the following error:
2019-06-08 11:33:48.746469: W tensorflow/core/util/ctc/ctc_loss_calculator.cc:144] No valid path found.
Is it because that the label should be shorter than input length referring to below?
https://stackoverflow.com/questions/45130184/ctc-loss-error-no-valid-path-found
If so, how can I modify train.py to solve this problem?
Thanks in advance~

**Comment by solivr** [comment]
Yes this is the reason.
The updated version checks for these possible errors before starting the training and ignores the offending samples.
