### ISSUE TITLE
One question of scared

### ISSUE THREAD

**Issue by kulina** [solivr/tf-crnn#52]
When I ran this program，I got this : “sacred.utils.SacredError: The configuration is read-only in a captured function!". So how can I solve this problem and run the program correctly?

**Comment by JarnoRFB** [comment]
At the top of your script, you should turn of the read only config containers.

```python
from sacred import SETTINGS
SETTINGS['CONFIG']['READ_ONLY_CONFIG'] = False
```

Read only configs are a safeguard against configurations being modified after the configuration was finalized. Alternatively to turning it of you can also make sure, that values inside the config dict get modified.
You are welcome to ask sacred related questions directly at https://github.com/IDSIA/sacred/issues or StackOverflow at https://stackoverflow.com/questions/tagged/python-sacred.
