### ISSUE TITLE
csv_delimiter bug

### ISSUE THREAD

**Issue by ghost** [solivr/tf-crnn#6]
in file train.py
`        parameters = Params(train_batch_size=128,
                            eval_batch_size=128,
                            learning_rate=1e-3,  # 1e-3 recommended
                            learning_decay_rate=0.95,
                            learning_decay_steps=5000,
                            evaluate_every_epoch=5,
                            save_interval=5e3,
                            input_shape=(32, 304),
                            optimizer='adam',
                            digits_only=False,
                            alphabet=Alphabet.LETTERS_DIGITS_EXTENDED,
                            alphabet_decoding='same',
                            csv_delimiter=' ',
                            csv_files_eval=args.get('csv_files_eval'),
                            csv_files_train=args.get('csv_files_train'),
                            output_model_dir=args.get('output_model_dir'),
                            n_epochs=args.get('nb_epochs'),
                            gpu=args.get('gpu')
                            )`
csv_delimiter should be assigned ' '

**Comment by solivr** [comment]
`csv_delimiter` is a parameter, so you can assign it to whatever you want. Just be consistant with your csv file. Besides, if your are training with sentences (where you have ' ' character) you may have trouble reading correctly your csv with `csv_delimiter=' '`, this is why I would recommend `;` for instance.
