### ISSUE TITLE
why calculate the seq_len_inputs by use img_width / 2*2

### ISSUE THREAD

**Issue by WenmuZhou** [solivr/tf-crnn#7]
![image](https://user-images.githubusercontent.com/12406017/32538260-58b02b46-c4a0-11e7-9950-1bdbaa445888.png)

the `seq_len_inputs` is the length of string in the input image or the pixels of single  character

**Comment by solivr** [comment]
`seq_len_input` is the length of input (image sequence) of the `tf.nn.ctc_loss`, i.e the width of the image after going through the model (`original_width/2*2 - 1`). To understand it better, have a look at your Tensorboard graph.

**Comment by WenmuZhou** [comment]
so,if the image contains mush non-text area , the `seq_len_input ` is longer than the true character. Will this lead to problems?, in other words, when I prepare my datasets, What should I pay attention to? Should the  picture be all text area and haven't non-text area? .can you peovide a email adress to communicate convenient

**Comment by solivr** [comment]
Even without 'non-text area', `seq_len_input` will usually be longer than the sequence of characters (one string-character is composed of several columns of pixels). I don't think this can cause big issues, but just in case, if you can, try to crop the text as close as possible. 
The only case that I think of where it may be annoying, is if you have examples where the last character of the sequence is ` ' ' ` and you're trying to learn that and at the same time you have other images with non-text area where the transcription is not ` ' ' `. Again, you should be as much consistant as possible in annotating your data.
